---
title: "Lab Problem Set 1"
author: "Rachel Byers"
date: "2026-01-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Installing Eudcation Data Package

```{r educationdata}
install.packages("educationdata")
install.packages("dplyr")
install.packages("forcats")
```

## Loading Packages 
```{r warning = FALSE}
library(educationdata)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(forcats)
```

## Endpoint Information
#https://educationdata.urban.org/api/v1/{topic}/{source}/{endpoint}/{year}/[additional_specifiers _or_disaggregators]/[optional filters]
#https://github.com/UrbanInstitute/education-data-package-r

## Creating Data Frame
```{r}
enrollmentdata <- get_education_data(level = 'schools', 
                         source = 'ccd', 
                         topic = 'enrollment',
                         filters = list(year = 2022,
                                        grade = 'grade-99'))
head(enrollmentdata)
```

## Data Frame
```{r}

```

## Enrollment Data Plots
```{r}
histo1 <- ggplot(enrollmentdata, aes(x = enrollment)) +
  geom_histogram(fill = "#56B4E9",
                 color = "white",
                 bins = 10)
histo1
histo2 <- ggplot(enrollmentdata, aes(x = enrollment)) +
  geom_histogram(fill = "red",
                 color = "white",
                 bins = 50)
histo2
density1 <- ggplot(enrollmentdata, aes(enrollment)) +
  geom_density(fill = "#56B4E9",
               bw = 5)
density1
density2 <- ggplot(enrollmentdata, aes(enrollment)) +
  geom_density(fill = "#56B4E9",
               bw = 1000) 
density2
```

## Re-loading births dataset from Lab 2
```{r}
firsthalf <- read.csv("C:\\Users\\missm\\Downloads\\US_births_1994-2003_CDC_NCHS.csv")
firsthalfdata <- data.frame(firsthalf)
firsthalfdata <- firsthalfdata[!(firsthalfdata$year %in% c("2000", "2001", "2002", "2003")), ]
secondhalf <- read.csv("C:\\Users\\missm\\Downloads\\US_births_2000-2014_SSA.csv")
secondhalfdata <- data.frame(secondhalf)
summary(secondhalfdata)
summary(firsthalfdata)
combined_data <- rbind(firsthalfdata, secondhalfdata)
summary(combined_data)
combined_data$month <- factor(
 combined_data$month,
 levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
 labels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
)
combined_data$day_of_week <- factor(
 combined_data$day_of_week,
 levels = c(1, 2, 3, 4, 5, 6, 7),
 labels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
)
tibble(combined_data)
```

## Grouping and Summarizing
```{r}
groupeddata <- combined_data %>%
  group_by(month, date_of_month) %>%
  summarise(
    Avg_Births = mean(births)
  )
groupeddata
```

##Creating Heat Maps 
```{r}
birthsheatmap <- ggplot(groupeddata, aes(date_of_month, month)) +
  geom_tile(aes(fill = Avg_Births))
birthsheatmap
birthsheatmap2 <- ggplot(groupeddata, aes(date_of_month, month)) +
  geom_tile(aes(fill = Avg_Births)) +
  scale_fill_viridis_c(option = "magma")
birthsheatmap2
birthsheatmap3 <- ggplot(groupeddata, aes(date_of_month, fct_reorder(month, Avg_Births))) +
  geom_tile(aes(fill = Avg_Births)) +
  scale_fill_viridis_c(option = "magma")
birthsheatmap3
```




